In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5,6,]

In [3]:
np.mean(x)

3.5

In [4]:
np.std(x)

1.707825127659933

In [5]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [6]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [12]:
y = [[1,2,3,4,4,5]]

In [13]:
np.multiply(x, y)

array([[ 1,  4,  9, 16, 20, 30]])

In [14]:
def abc(x):
    return x**2 - 5.76

In [22]:
abc(2.40)

0.0

In [23]:
def xyz (x):
    return x**2 -20.6*x + 106.09

In [37]:
xyz(10.3)

-1.4210854715202004e-14